### ISSUE TITLE
Argo CD CR Updates (Application Sets and requests/limits)

### ISSUE THREAD

**Issue by nasx** [uc2-io/uc2-gitops#3]
Better enablement of Application Sets with the following:

```yaml
spec:
  applicationSet:
    enabled: true
    resources:
      limits: {}
      requests: {}
    sourceNamespaces: []
```

Also review `limits` for various components. `cpu` can probably be tuned down significantly.
