### ISSUE TITLE
Argo CD Chart Updates - Expose extraConfig

### ISSUE THREAD

**Issue by nasx** [uc2-io/uc2-gitops#4]
Add `extraConfig` to templates to support passing recommended configurations to Argo CD for Kyverno.

```yaml
  extraConfig:
    resource.compareoptions: |
      ignoreAggregatedRoles: true
```
